# Generated by Django 6.0.4 on 2026-04-16 16:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=255)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='practices.practice')),
            ],
        ),
    ]
