# Generated by Django 6.0.4 on 2026-04-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0002_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='practice',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='practice',
            name='npi_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='practice',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='practice',
            name='tax_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
