# Generated by Django 6.0.4 on 2026-04-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0003_alter_practice_email_alter_practice_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='practice',
        ),
        migrations.AddField(
            model_name='provider',
            name='practices',
            field=models.ManyToManyField(blank=True, related_name='providers', to='practices.practice'),
        ),
    ]
