# Generated by Django 6.0.4 on 2026-04-17 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0004_remove_provider_practice_provider_practices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('default', 'Default'), ('medical_director', 'Medical Director')], default='default', max_length=20)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_practices', to='practices.practice')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_practices', to='practices.provider')),
            ],
            options={
                'unique_together': {('provider', 'practice')},
            },
        ),
        migrations.AlterField(
            model_name='provider',
            name='practices',
            field=models.ManyToManyField(blank=True, related_name='providers', through='practices.ProviderPractice', to='practices.practice'),
        ),
    ]
