# Generated by Django 6.0.4 on 2026-04-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0006_rename_providerpractice_to_providerbypractice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerbypractice',
            name='type',
            field=models.CharField(choices=[('default', 'Default'), ('medical_director', 'Medical Director')], default='default', max_length=20),
        ),
    ]
