# Generated by Django 6.0.4 on 2026-04-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0009_merge_0007_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='title',
            field=models.CharField(blank=True, default='Uncredentialed', max_length=100),
        ),
        migrations.AlterField(
            model_name='providerbypractice',
            name='type',
            field=models.CharField(choices=[('default', 'Default'), ('medical_director', 'Medical Director')], default='default', max_length=20),
        ),
    ]
