# Generated by Django 6.0.4 on 2026-04-17 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0011_backfill_provider_title_uncredentialed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='practices.provider')),
            ],
        ),
    ]
