# Generated by Django 6.0.4 on 2026-04-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0012_add_credential_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credential',
        ),
    ]
