# Generated by Django 6.0.4 on 2026-04-17 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0013_make_credential_abstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeaCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(blank=True, default='', max_length=100)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('enumeration_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='credentials/')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dea_credentials', to='practices.provider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NpiCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(blank=True, default='', max_length=100)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('enumeration_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='credentials/')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npi_credentials', to='practices.provider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
