# Generated by Django 6.0.4 on 2026-04-17 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0014_add_npi_dea_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deacredential',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='npicredential',
            name='provider',
        ),
        migrations.AddField(
            model_name='provider',
            name='dea_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_providers', to='practices.deacredential'),
        ),
        migrations.AddField(
            model_name='provider',
            name='npi_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_providers', to='practices.npicredential'),
        ),
    ]
