# Generated by Django 6.0.4 on 2026-04-16 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_Initial'),
        ('practices', '0003_alter_practice_email_alter_practice_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='practices.practice'),
        ),
    ]
