# Generated by Django 6.0.4 on 2026-04-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vida_verified', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrequest',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reportrequest',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='reportrequest',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='reportrequest',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reportrequest',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
