# Generated by Django 6.0.4 on 2026-04-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vida_verified', '0002_reportrequest_city_reportrequest_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrequest',
            name='ein',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='reportrequest',
            name='id_type',
            field=models.CharField(blank=True, choices=[('SSN', 'SSN'), ('EIN', 'EIN')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='reportrequest',
            name='ssn',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
