# Generated by Django 6.0.4 on 2026-04-13 20:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vida_verified', '0004_dcdcredentialstatus_npicredentialstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcdcredentialstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dcdcredentialstatus',
            name='dea_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='dcdcredentialstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
