# Generated by Django 6.0.4 on 2026-04-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vida_verified', '0005_dcdcredentialstatus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='npicredentialstatus',
            name='json_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='npicredentialstatus',
            name='npi_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
