# Generated by Django 6.0.4 on 2026-04-13 20:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vida_verified', '0006_npicredentialstatus_json_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='npicredentialstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npicredentialstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
