# Generated by Django 6.0.4 on 2026-04-13 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vida_verified', '0007_npicredentialstatus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcdcredentialstatus',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vida_verified.report'),
        ),
        migrations.AddField(
            model_name='npicredentialstatus',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vida_verified.report'),
        ),
    ]
