# Generated by Django 6.0.4 on 2026-04-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vida_verified', '0008_dcdcredentialstatus_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcdcredentialstatus',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=24),
        ),
        migrations.AddField(
            model_name='npicredentialstatus',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=24),
        ),
    ]
