# Generated by Django 6.0.4 on 2026-04-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vida_verified', '0009_dcdcredentialstatus_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcdcredentialstatus',
            name='json_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
