# Generated by Django 6.0.4 on 2026-04-14 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vida_verified', '0010_dcdcredentialstatus_json_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='request',
        ),
        migrations.CreateModel(
            name='ContinuousReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(max_length=24)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='continuous_report', to='vida_verified.reportrequest')),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=24)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_report', to='vida_verified.reportrequest')),
            ],
        ),
        migrations.AlterField(
            model_name='dcdcredentialstatus',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vida_verified.onetimereport'),
        ),
        migrations.DeleteModel(
            name='NpiCredentialStatus',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
