# Generated by Django 6.0.4 on 2026-04-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vida_verified', '0011_remove_report_request_continuousreport_onetimereport_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DcdCredentialStatus',
        ),
    ]
