# Generated by Django 6.0.4 on 2026-04-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vida_verified', '0012_delete_dcdcredentialstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
