# Generated by Django 6.0.4 on 2026-04-14 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vida_verified', '0014_monitorresults_delete_continuousreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=24)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_results', to='vida_verified.reportrequest')),
            ],
        ),
        migrations.DeleteModel(
            name='OneTimeReport',
        ),
    ]
