# Generated by Django 6.0.4 on 2026-04-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vida_verified', '0016_fix_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorResultsView',
            fields=[
                ('monitor_results_id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=24)),
                ('results_created_at', models.DateTimeField()),
                ('results_updated_at', models.DateTimeField()),
                ('request_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('ssn', models.CharField(max_length=11)),
                ('ein', models.CharField(max_length=10)),
                ('id_type', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=24)),
                ('request_created_at', models.DateTimeField()),
                ('request_updated_at', models.DateTimeField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportResultsView',
            fields=[
                ('report_results_id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=24)),
                ('results_created_at', models.DateTimeField()),
                ('request_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('ssn', models.CharField(max_length=11)),
                ('ein', models.CharField(max_length=10)),
                ('id_type', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=24)),
                ('request_created_at', models.DateTimeField()),
                ('request_updated_at', models.DateTimeField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
