# Generated by Django 6.0.4 on 2026-04-15 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vida_verified', '0023_remove_monitorresults_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorresults',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='reportresults',
            name='request_id',
        ),
    ]
