# Generated by Django 6.0.4 on 2026-04-13 19:31

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vida_verified', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vida_verified.report',),
        ),
        migrations.CreateModel(
            name='ReportRequestProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Report Request',
                'verbose_name_plural': 'Report Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vida_verified.reportrequest',),
        ),
    ]
