# Generated by Django 6.0.4 on 2026-04-13 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportProxy',
        ),
        migrations.DeleteModel(
            name='ReportRequestProxy',
        ),
    ]
